language: java
notifications:
  slack:
    secure: xIxPtCmvmPi1ZcBShXleoxlrNltl2GC46fubZMIP01l/sLL5ddPPgyGchh5bk9pCjIMQ8ElbSMrUSY0gUK9KPCe9JtQjfjp06kjP//4qS8v5toEUNevi336mnx+VEQAW0hW27Aa9sfCHsNYO/f5dODkKGZuYwqkhjuQ+67khGJQ=
deploy:
  provider: releases
  api_key:
    secure: DegRwl8afRtv4G+iG15e+ZhOCk+H6kOe2lDZCMjpOcKqu9nM2uOSdSZN//gqVFoyiIISLdReQaeB1+sFYlxzxxgByLWjirkdzoCYhtGm6gHoQ9Ua+P80WdtJPwp4x9m+DXjiqu5JgoNiEVQ1BB/KedYXfY0pjR7Yvd5xbEvbNZQ=
  file: build/distributions/xld-liquibase-plugin-5.0.1-SNAPSHOT.xldp
  skip_cleanup: true
  on:
    repo: xebialabs-community/xld-liquibase-plugin
    all_branches: true
    tags: true
